config/routes.rb
ClearMyCache::Application.routes.draw do

  devise_for :users
  resources :cmcbrowsers
  resources :cmcplatforms

  root 'cmcinstruction#index'
  get 'all_supported_browsers' => 'cmcinstruction#display_all', :as => 'display_all'
  get 'contribute' => 'cmcinstruction#contribute', :as => 'contribute'
  get ':cmcplatform_slug/:cmcplatform_version/:cmcbrowser_slug/:cmcbrowser_version' => 'cmcinstruction#display', :as => 'display'

  

end

app/models/cmcbrowser.rb
class Cmcbrowser < ActiveRecord::Base
	belongs_to :cmcplatform

	#validates :name, :presence => true, :format => {:with => /^[a-z ]+$/i, :message => 'Must only contain letters and spaces'}

	validates :slug, :presence => true, 
                     :format => {
                     	:with => /\A[a-z\-_]+\z/,
                     	:message => 'Must only be lowercase letters, hyphens and underscores'
                     }
    validates :name, :presence => true, 
                     :format => {
                     	:with => /\A[a-z\- ]+\z/i,
                     	:message => 'Must only be letters, spaces and hyphens'
                     }

    validates :howto, :presence => true
    validates :version, :presence => true

    validates :version, :numericality => { :greater_than => 0, :message => 'version must be more then 0' }

	validates_uniqueness_of :name, :scope => [:slug, :version, :cmcplatform_id]
end

app/models/cmcplatform.rb
class Cmcplatform < ActiveRecord::Base
	has_many :cmcbrowsers, :class_name => 'Cmcbrowser',
    :foreign_key => 'cmcplatform_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout "subpage"
end

app/controllers/cmcbrowsers_controller.rb
class CmcbrowsersController < ApplicationController
  before_action :set_cmcbrowser, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /cmcbrowsers
  # GET /cmcbrowsers.json
  def index
    @cmcbrowsers = Cmcbrowser.all
  end

  # GET /cmcbrowsers/1
  # GET /cmcbrowsers/1.json
  def show
  end

  # GET /cmcbrowsers/new
  def new
    @cmcbrowser = Cmcbrowser.new
  end

  # GET /cmcbrowsers/1/edit
  def edit
  end

  # POST /cmcbrowsers
  # POST /cmcbrowsers.json
  def create
    @cmcbrowser = Cmcbrowser.new(cmcbrowser_params)

    respond_to do |format|
      if @cmcbrowser.save
        format.html { redirect_to @cmcbrowser, notice: 'Cmcbrowser was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cmcbrowser }
      else
        format.html { render action: 'new' }
        format.json { render json: @cmcbrowser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cmcbrowsers/1
  # PATCH/PUT /cmcbrowsers/1.json
  def update
    respond_to do |format|
      if @cmcbrowser.update(cmcbrowser_params)
        format.html { redirect_to @cmcbrowser, notice: 'Cmcbrowser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cmcbrowser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cmcbrowsers/1
  # DELETE /cmcbrowsers/1.json
  def destroy
    @cmcbrowser.destroy
    respond_to do |format|
      format.html { redirect_to cmcbrowsers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cmcbrowser
      @cmcbrowser = Cmcbrowser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cmcbrowser_params
      params.require(:cmcbrowser).permit(:name, :slug, :version, :howto, :cmcplatform_id)
    end
end

app/controllers/cmcinstruction_controller.rb
class CmcinstructionController < ApplicationController
  layout "application", except: [:index, :display_all, :contribute]

  def index
    redirect_to :action => 'display', 
  					:cmcplatform_slug => browser.platform.downcase, 
  					:cmcplatform_version => '1', # I can't get the platform version right now :(
  					:cmcbrowser_slug => browser.name.downcase.parameterize, 
  					:cmcbrowser_version => browser.version
  end

  def display
    # Override the default all slug with mac
    if params[:cmcplatform_slug]
      params[:cmcplatform_slug] = 'mac'
    end

  	@cmc_browser = Cmcbrowser.where("slug = :slug", {slug: params[:cmcbrowser_slug]}).order("ABS((#{params[:cmcbrowser_version]} - version)) DESC").limit(1).first;
    @cmc_platform = Cmcplatform.where("slug = :slug", {slug: params[:cmcplatform_slug]}).limit(1).first;

    if @cmc_browser.nil? or @cmc_platform.nil?
      render :file => "public/404.html",  :status => 404
    else
      @canonical_url = display_url(
        :cmcplatform_slug => @cmc_platform.slug, 
        :cmcplatform_version => 1,
        :cmcbrowser_slug => @cmc_browser.slug, 
        :cmcbrowser_version => @cmc_browser.version,
      )

      @body_class = @cmc_platform.slug + " " + @cmc_browser.slug;
    end
  end

  def display_all
    @cmc_browsers = Cmcbrowser.all()
    @cmc_platforms = Cmcplatform.where("slug != :slug", {slug: 'all'})
  end

  def contribute

  end
end

app/controllers/cmcplatforms_controller.rb
class CmcplatformsController < ApplicationController
  before_action :set_cmcplatform, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /cmcplatforms
  # GET /cmcplatforms.json
  def index
    @cmcplatforms = Cmcplatform.all
  end

  # GET /cmcplatforms/1
  # GET /cmcplatforms/1.json
  def show
  end

  # GET /cmcplatforms/new
  def new
    @cmcplatform = Cmcplatform.new
  end

  # GET /cmcplatforms/1/edit
  def edit
  end

  # POST /cmcplatforms
  # POST /cmcplatforms.json
  def create
    @cmcplatform = Cmcplatform.new(cmcplatform_params)

    respond_to do |format|
      if @cmcplatform.save
        format.html { redirect_to @cmcplatform, notice: 'Cmcplatform was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cmcplatform }
      else
        format.html { render action: 'new' }
        format.json { render json: @cmcplatform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cmcplatforms/1
  # PATCH/PUT /cmcplatforms/1.json
  def update
    respond_to do |format|
      if @cmcplatform.update(cmcplatform_params)
        format.html { redirect_to @cmcplatform, notice: 'Cmcplatform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cmcplatform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cmcplatforms/1
  # DELETE /cmcplatforms/1.json
  def destroy
    @cmcplatform.destroy
    respond_to do |format|
      format.html { redirect_to cmcplatforms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cmcplatform
      @cmcplatform = Cmcplatform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cmcplatform_params
      params.require(:cmcplatform).permit(:name, :slug, :version, :howto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def canonical_link_tag
	  tag(:link, :rel => :canonical, :href => @canonical_url) if @canonical_url
	end

	def body_class
		@body_class if @body_class
	end
end

app/helpers/cmcbrowsers_helper.rb
module CmcbrowsersHelper
end

app/helpers/cmcinstruction_helper.rb
module CmcinstructionHelper
end

app/helpers/cmcplatforms_helper.rb
module CmcplatformsHelper
end

app/views/cmcbrowsers/_form.html.erb
<%= simple_form_for(@cmcbrowser) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :slug %>
    <%= f.input :version %>
    <%= f.input :howto %>
    <%= f.input :cmcplatform_id, collection: Cmcplatform.all %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cmcbrowsers/edit.html.erb
<h1>Editing cmcbrowser</h1>

<%= render 'form' %>

<%= link_to 'Show', @cmcbrowser %> |
<%= link_to 'Back', cmcbrowsers_path %>

app/views/cmcbrowsers/index.html.erb
<h1>Listing cmcbrowsers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Version</th>
      <th>Howto</th>
      <th>Cmcplatform</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cmcbrowsers.each do |cmcbrowser| %>
      <tr>
        <td><%= cmcbrowser.name %></td>
        <td><%= cmcbrowser.slug %></td>
        <td><%= cmcbrowser.version %></td>
        <td><%= cmcbrowser.howto %></td>
        <td><%= cmcbrowser.cmcplatform.name %></td>
        <td><%= link_to 'Show', cmcbrowser %></td>
        <td><%= link_to 'Edit', edit_cmcbrowser_path(cmcbrowser) %></td>
        <td><%= link_to 'Destroy', cmcbrowser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cmcbrowser', new_cmcbrowser_path %>

app/views/cmcbrowsers/new.html.erb
<h1>New cmcbrowser</h1>

<%= render 'form' %>

<%= link_to 'Back', cmcbrowsers_path %>

app/views/cmcbrowsers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cmcbrowser.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @cmcbrowser.slug %>
</p>

<p>
  <strong>Version:</strong>
  <%= @cmcbrowser.version %>
</p>

<p>
  <strong>Howto:</strong>
  <%= @cmcbrowser.howto %>
</p>

<p>
  <strong>Cmcplatform:</strong>
  <%= @cmcbrowser.cmcplatform.name %>
</p>

<%= link_to 'Edit', edit_cmcbrowser_path(@cmcbrowser) %> |
<%= link_to 'Back', cmcbrowsers_path %>

app/views/cmcinstruction/contribute.html.erb
<div class="content">
	<h1>How to Contribute</h1>
	<p>Contributing to Clear My Cache is easy, just <%= link_to 'sign up', new_user_registration_path %> / <%= link_to 'login', new_user_session_path %> .</p>
</div>

app/views/cmcinstruction/display.html.erb
<section id="what_am_i">
   <hgroup>
      <h2>Hello <%= browser.platform %> User!</h2>
      <% if browser.name == 'Internet Explorer' %>
         <h3>You&rsquo;re using <%= browser.name %>, get in!</h3>
      <% elsif browser.name == 'Chrome' %> 
         <h3>You&rsquo;re using <%= browser.name %>, check you out!</h3>
      <% else %>
         <h3>You&rsquo;re using <%= browser.name %>, Winning!</h3>
      <% end %>
   </hgroup>
   <% if browser.name == 'Internet Explorer' %>
   <p class="update">However, the new Firefox is out now! <a href="http://www.mozilla.org/en-US/">Get it here</a></p>
   <% end %>
</section>
<section id="how_to_clear">
   <div class="sleeve">
      <h2>Here&rsquo;s how you clear your cache for &hellip;</h2>
      <section id="your_headers">
         <header class="browser">
            <img src="/assets/img/browsers/<%= @cmc_browser.slug %>.png" alt="<%= @cmc_browser.name %> Icon"/>
            <h3><span>Your browser, </span><%= @cmc_browser.name %></h3>
            <a href="#your_browser" class="skip">Skip to your Browser instructions</a>
         </header>
         <header class="os">
            <img src="/assets/img/os/<%= @cmc_platform.slug %>.png" alt="<%= @cmc_platform.name %> Icon"/>
            <h3><span>Your Operating System, </span><%= @cmc_platform.name %></h3>
            <a href="#your_os" class="skip">Skip to your Operating System instructions</a>
         </header>
      </section>
      <section class="how_tos">
         <section id="your_browser" class="how_to">
            <%= raw(@cmc_browser.howto) %>
         </section>
         <section id="your_os" class="how_to">
            <%= raw(@cmc_platform.howto) %>
         </section>
      </section>
   </div>
</section>

<img src="/assets/img/bgs/<%= @cmc_browser.slug %>.png" alt="<%= @cmc_browser.name %>" id="browser_image"/>

app/views/cmcinstruction/display_all.html.erb
<div class="content">
	<h1>All supported setups</h1>
	<div class="row">
		<div class="col-6">
			<h2>Browsers</h2>
			<ul>
				<% @cmc_browsers.each do |cmc_browser| %>
					<% if !cmc_browser.cmcplatform.nil? then %>
					<li><%= link_to display_path(:cmcplatform_slug => cmc_browser.cmcplatform.slug, :cmcplatform_version => "1", :cmcbrowser_slug => cmc_browser.slug, :cmcbrowser_version => cmc_browser.version) do %>
							<%= cmc_browser.name %> <%= cmc_browser.version %>
							<% if cmc_browser.cmcplatform.slug != 'all'  %>, <%= cmc_browser.cmcplatform.name %> <% end %>
						<% end %>

						<% if user_signed_in? %>
							<small>(<%= link_to 'Edit', edit_cmcbrowser_path(:id => cmc_browser.id) %>)</small>
						<% end %>
					</li>
					<% end %>
				<% end %>
			</ul>

			<br /><br />
			<%= link_to_if(user_signed_in?, 'Add new browser', new_cmcbrowser_path){} %>
		</div>

		<div class="col-6">
			<h2>Platforms</h2>
			<ul>
				<% @cmc_platforms.each do |cmc_platform| %>
					<li><% if !cmc_platform.cmcbrowsers.empty? %>
						<%= link_to display_path(:cmcplatform_slug => cmc_platform.slug, :cmcplatform_version => "1", :cmcbrowser_slug => cmc_platform.cmcbrowsers[0].slug, :cmcbrowser_version => cmc_platform.cmcbrowsers[0].version) do %>
							<%= cmc_platform.name %>
						<% end %>
					<% else %>
						<%= cmc_platform.name %>
					<% end %>

					<% if user_signed_in? %>
						<small>(<%= link_to 'Edit', edit_cmcplatform_path(:id => cmc_platform.id) %>)</small>
					<% end %>
				</li>
				<% end %>

				<br /><br />
				<%= link_to_if(user_signed_in?, 'Add new platform', new_cmcplatform_path){} %>
			</ul>
		</div>
	</div>
</div>

app/views/cmcinstruction/index.html.erb
<h1>Cmcinstruction#index</h1>
<p>Find me in app/views/cmcinstruction/index.html.erb</p>

app/views/cmcplatforms/_form.html.erb
<%= simple_form_for(@cmcplatform) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :slug %>
    <%= f.input :howto %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cmcplatforms/edit.html.erb
<h1>Editing cmcplatform</h1>

<%= render 'form' %>

<%= link_to 'Show', @cmcplatform %> |
<%= link_to 'Back', cmcplatforms_path %>

app/views/cmcplatforms/index.html.erb
<h1>Listing cmcplatforms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Version</th>
      <th>Howto</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cmcplatforms.each do |cmcplatform| %>
      <tr>
        <td><%= cmcplatform.name %></td>
        <td><%= cmcplatform.slug %></td>
        <td><%= cmcplatform.howto %></td>
        <td><%= link_to 'Show', cmcplatform %></td>
        <td><%= link_to 'Edit', edit_cmcplatform_path(cmcplatform) %></td>
        <td><%= link_to 'Destroy', cmcplatform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cmcplatform', new_cmcplatform_path %>

app/views/cmcplatforms/new.html.erb
<h1>New cmcplatform</h1>

<%= render 'form' %>

<%= link_to 'Back', cmcplatforms_path %>

app/views/cmcplatforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cmcplatform.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @cmcplatform.slug %>
</p>

<p>
  <strong>Howto:</strong>
  <%= @cmcplatform.howto %>
</p>

<%= link_to 'Edit', edit_cmcplatform_path(@cmcplatform) %> |
<%= link_to 'Back', cmcplatforms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clear My Cache</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application_header" %>
  <%= csrf_meta_tags %>
  <%= canonical_link_tag %>

</head>
<body id="home" class="<%= body_class %>">

	<header id="mast">
		<div class="sleeve">
			<h1><a href="/" id="logo"><span>Clear My Cache</span></a></h1>
		</div>
	</header>

	<% if notice || alert %>
		<div class="content">
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
		</div>
	<% end %>

	<%= yield %>

	<footer id="footer">
		<div class="sleeve">
			<p>Clear My Cache is a free service brought to you by <a href="http://twitter.com/MikeRogers0/">Mike</a>, <a href="http://www.twitter.com/de/">Dan</a>, <a href="http://twitter.com/Lletnek/">Tom</a> &amp; <a href="http://twitter.com/HarryWiseman/">Harry</a>.</p>
			<small>All logos are copyright of their respective owners. Clear My Cache accept no liability for any damages or losses incurred while following the advice on this website.</small>
		</div>
	</footer>
<%= javascript_include_tag "application_footer" %>
</body>
</html>

app/views/layouts/sections/_footer.html.erb
	<footer id="footer">
		<div class="sleeve">
			<p>Clear My Cache is a free service brought to you by <a href="http://twitter.com/MikeRogers0/">Mike</a>, <a href="http://www.twitter.com/de/">Dan</a>, <a href="http://twitter.com/Lletnek/">Tom</a> &amp; <a href="http://twitter.com/HarryWiseman/">Harry</a>.</p>
			<small><%= link_to 'All supported setups', display_all_path  %> | 
				<% if user_signed_in? %>
					<%= link_to 'Your Account', edit_user_registration_path %> | 
					<%= link_to 'Log Out', destroy_user_session_path, :method => :delete  %>
				<% else %>
					<%= link_to 'Sign In', new_user_session_path %> | <%= link_to 'Sign Up to Contribute', new_user_registration_path %>
				<% end %>
				<br />
				All logos are copyright of their respective owners. Clear My Cache accept no liability for any damages or losses incurred while following the advice on this website.</small>
		</div>
	</footer>
<%= javascript_include_tag "application_footer" %>
</body>
</html>

app/views/layouts/sections/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clear My Cache</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application_header" %>
  <%= csrf_meta_tags %>
  <%= canonical_link_tag %>

</head>
<body id="home" class="<%= body_class %>">

	<header id="mast">
		<div class="sleeve">
			<h1><a href="/" id="logo"><span>Clear My Cache</span></a></h1>
		</div>
	</header>

	<% if notice || alert %>
		<div class="content">
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
		</div>
	<% end %>

app/views/layouts/subpage.html.erb
<%= render 'layouts/sections/header' %>
	<div class="content">
		<%= yield %>
	</div>
<%= render 'layouts/sections/footer' %>